# Generated by Django 6.0.2 on 2026-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orderdetails_sweetness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Assistant manager', 'Assistant manager'), ('Sales', 'Sales')], max_length=100, null=True),
        ),
    ]

